site_name: "CSCI 305: Concepts of Programming Languages"
site_url: "http://localhost:8080/"
# site_url: "https://cs.montana.edu/revelle/courses/csci305/"

theme:
  name: cinder
  custom_dir: cinder/
  highlightjs: true
  disable_footer: true

nav:
  - Home: index.md

extra_css:
  - style.css